### ISSUE TITLE
cannot import name 'Mode' from 'ardupilot_msgs.msg

### ISSUE THREAD

**Issue by waqaszaidi** [ethz-asl/terrain-navigation#70]
Whenever I tried to run mavros_dds_bridge.py. It gives error from
ardupilot_msgs.msg import Mode
ImportError: cannot import name 'Mode' from 'ardupilot_msgs.msg' (/home/waqas/ros2_ws/install/ardupilot_msgs/local/lib/python3.10/dist-packages/ardupilot_msgs/msg/__init__.py)

**Comment by Jaeyoung-Lim** [comment]
@waqaszaidi Please provide more details on your setup. Are you running ros2? ros1? which autopilot are you running?

Since I am not so familiar with Ardupilot, do you have any insights @Ryanf55 @srmainwaring ?

**Comment by waqaszaidi** [comment]
Thankyou very much for quick response @Jaeyoung-Lim @srmainwaring 

I am little new, I want to run the planner with ardupilot, so i am having some basic question
Does it needs modification. Since I am following guide which is present in https://discuss.ardupilot.org/t/offboard-terrain-navigation-for-plane-with-ros-2-ap-dds/114418.

First I setup according to  https://ardupilot.org/dev/docs/ros2-sitl.html and I was able to get ardupilot_dds node
Then I switched to https://github.com/srmainwaring/ardupilot/tree/wips/wip-terrain-nav and rebuild workspace, now I am not getting any node in ros2 node list. Arduplane is working fine in sitl with mavproxy

Next according to guide I need to run the mavros_dds_bridge.py but It is giving me error 

ardupilot_msgs.msg import Mode
ImportError: cannot import name 'Mode' from 'ardupilot_msgs.msg' (/home/waqas/ros2_ws/install/ardupilot_msgs/local/lib/python3.10/dist-packages/ardupilot_msgs/msg/init.py)

[terrain_planner_node-1] Requesting global origin messages
[terrain_planner_node-1] [WARN] [1725444728.768731029] [terrain_planner]: Service [/mavros/cmd/command] not available.

**Comment by Ryanf55** [comment]
I can put together a patch.

**Comment by waqaszaidi** [comment]
Hello @Ryanf55 @srmainwaring. I just want to ask why the arduplane not follow the path made by the planner. It just revolve around the path and keeps on decreasing the height and unable to reach the Goal State?

**Comment by Jaeyoung-Lim** [comment]
@waqaszaidi Was the problem solved? Could you explain how you solved your issue?

**Comment by waqaszaidi** [comment]
> @waqaszaidi Was the problem solved? Could you explain how you solved your issue?

Yes, Just need to comment out few lines of code in mavros_dds_bridg, Since a service is already there to Switch Mode as mentioned by @srmainwaring 

Comment out these lines and you are good to go

`  from ardupilot_msgs.msg import Mode
self.mode_sub = self.create_subscription(
                Mode,
                "/ap/mode",
                self.mode_cb,
                10,
            )`

**Comment by Jaeyoung-Lim** [comment]
@waqaszaidi Thanks for the update!
